# Generated by Django 4.0.6 on 2023-02-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=128)),
                ('os', models.CharField(max_length=16)),
                ('activated', models.BooleanField(default=False)),
                ('first_login_time', models.DateTimeField(verbose_name='date published')),
                ('activation_time', models.DateTimeField(null=True, verbose_name='date published')),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.credential')),
            ],
        ),
    ]
